const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Shirt',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: 'images/p2.jpg',
      price: 240,
      countInStock: 150,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 6,
      description: 'High Quality Pants',
    },
    {
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: 'images/p3.jpg',
      price: 220,
      countInStock: 23,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 10,
      description: 'High Quality Pants',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: 'images/p4.jpg',
      price: 224,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 44,
      description: 'High Quality Shirt',
    },
  ],
};

export default data;
